### ISSUE TITLE
Unsure what the problem is.

### ISSUE THREAD

**Issue by darrylfillion** [autodesk-platform-services/aps-bim360-project-setup#3]
Hey,

I just tried to use the old version of this (Forge 1.7ish), which I've used for several years. That version is now saying it needs OAuth V2 which I have no idea how to make work.

So I decided to download and install the current version here hoping it fixed the problem but I am getting different errors (see image). Error 1 circled in red is extra characters in the first line which are certainly not in the batch file. Error 2 looks an awful lot like its struggling with the same lines of code as the old version was for OAuth V2, but I am not well versed in this at all and it does not directly mention OAuth V2 anymore.

![Screenshot 2024-07-30 151709](https://github.com/user-attachments/assets/80c9eab8-f827-4625-a0a9-895e995e64c7)

**Comment by darrylfillion** [comment]
I believe I can get the Batch file reading correctly by taking the old batch file and just pasting the new Set APS things. The other thing, no idea.

**Comment by joefields** [comment]
You may need to update your NuGet packages. I was getting the similar red error until I updated RestSharp to 108.0.1

You may also have to downgrade to that version of RestSharp as I had some other errors pop up with 111.4.1

**Comment by darrylfillion** [comment]
"update to new SDK for Authorization" fixed the issue. RestSharp was updated to 111.4.1 as per the comment above in this release of the code.

**Comment by darrylfillion** [comment]
see above
